version: '3.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
          POSTGRES_DB: rainbow_database
          POSTGRES_UESR: unicorn_user
          POSTGRES_PASSWORD: magical_password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_restapi
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: golang_restapi
    restart: always
    ports:
      - '9000:9000'
  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

volumes:
  database-data:
  grafana-storage:
  prometheus_data: